language: python
env:
  - TOXENV=py27
  - TOXENV=pep8
  - TOXENV=cover
  - TOXENV=docs
install:
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOX_ENV

after_success:
  - if [ "x$TOX_ENV" = 'xcover' ]; then coveralls; fi
